layout_spectrum: 0.2275986
typography_spectrum: 0.8996416
color:
  saturation: 0.3154122
  lightness: 0
  brandStrength: 0.9659498
  rhythmicContrast: 1
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'Privat mattelærer i Oslo '
